set_property IOSTANDARD LVCMOS33 [get_ports clk100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property IOSTANDARD LVCMOS33 [get_ports debug1]
set_property IOSTANDARD LVCMOS33 [get_ports debug2]
set_property PACKAGE_PIN Y18 [get_ports clk100MHz]
set_property PACKAGE_PIN A19 [get_ports speaker]
set_property PACKAGE_PIN A21 [get_ports debug1]
set_property PACKAGE_PIN E22 [get_ports debug2]
